version: "3.0"
services:
  postgresdb:
    image: postgres
    container_name: posgresdb-container
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - internalnet
    volumes:
      - C:/Users/promact/postgresdatabase:/var/lib/postgresql/data

  nextjsapp:
    build:
      context: ./
      dockerfile: Dockerfile
    image: nextjsapp:1.0
    expose:
      - ${SERVER_PORT}
    ports:
      - 3000:${SERVER_PORT}
    command: >
      sh -c "npx prisma db push
            npm run dev"
    environment:
      DATABASE_URL: ${REMOTE_DATABASE_URL}
      AUTH0_SECRET: ${AUTH0_SECRET}
      AUTH0_BASE_URL: ${AUTH0_BASE_URL}
      AUTH0_ISSUER_BASE_URL: ${AUTH0_ISSUER_BASE_URL}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
    depends_on:
      - postgresdb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge