import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { Toaster } from "react-hot-toast";
import { Sidebar } from "@/components/sidebar/Sidebar";
import { ThemeProvider } from "@/providers/ThemeProvider";
import LoginModal from "@/components/modals/CreateModal";
import CreateModal from "@/components/modals/CreateModal";

const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


/**
 * Renders the application layout with the given children.
 * @param children - the application content to render
 */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={`${font.className} bg-neutral-200 overflow-x-hidden`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="light"
            disableTransitionOnChange
          >
            <CreateModal/>
            <Toaster/>
            {children}
          </ThemeProvider>
          
        </body>
      </UserProvider>
    </html>
  );
}
