import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import '@/app/globals.css'
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { Toaster } from "react-hot-toast";
import { Sidebar } from "@/components/sidebar/Sidebar";
import { ThemeProvider } from "@/providers/ThemeProvider";
import CreateModal from "@/components/modals/createModals/CreateModal";
import { Navbar } from "@/components/navbar/Navbar";
import { initialProfile } from "@/lib/initial-profile";
import SuccessModal from "@/components/modals/SuccessModal";
import NameModal from "@/components/modals/createModals/NameModal";
import { ProfileModal } from "@/components/modals/ProfileModal";
import { EmployeesModal } from "@/components/modals/EmployeesModal";

const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cleo",
  description: "Generated by create next app",
};


/**
 * Renders the application layout with the given children.
 * @param children - the application content to render
 */

export default async function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = await initialProfile();

  return (
    <html lang="en" >
      <UserProvider>
        <body className={`${font.className} bg-neutral-900 overflow-x-hidden`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="light"
            disableTransitionOnChange
          >
            <CreateModal user={user}/>
            <SuccessModal/>
            <NameModal user={user}/>
            <ProfileModal user={user}/>
            <EmployeesModal user={user}/>
            <Toaster/>
            <div>
              <div className="h-screen">
                <div className=" w-full h-full flex items-center justify-between">
                  <div className="bg-neutral-200 dark:bg-black w-[15%] h-full flex items-center justify-center pr-1">
                    <div className="h-full w-full">
                      <Sidebar user={user}/>
                    </div>
                  </div>
                  <div className="bg-white dark:bg-neutral-900 w-[85%] h-full flex items-center justify-center pl-1">
                    <div className=" dark:bg-neutral-900 h-full w-full">
                      <div className="w-full h-[10%] p-5">
                        <Navbar user={user}/>
                      </div>
                      <div className="w-full h-[90%] ">
                        {children}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </ThemeProvider>
        </body>
      </UserProvider>
    </html>
  );
}
