import getProjectsByUsertId from "@/actions/getProjects/getProjectByUserId";
import { ProjectClient } from "@/components/pages/projects/ProjectClient";
import { initialProfile } from "@/lib/initial-profile";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Customer sucess",
  description: "Generated by create next app",
};


/**
 * Renders the application layout with the given children.
 * @param children - the application content to render
 */

export default async function ProjectsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const user = await initialProfile()
    const projects = await getProjectsByUsertId()

  return (
    <div className=" h-full w-full">
        <div className=" w-full h-full">
          {children}  
        </div>
        
    </div>
  );
}
