import getProjectsByUsertId from "@/actions/getProjects/getProjectByUserId";
import EmptyState from "@/components/pages/EmptyState";
import { ProjectClient } from "@/components/pages/projects/ProjectClient";
import { initialProfile } from "@/lib/initial-profile";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Customer sucess",
  description: "Generated by create next app",
};


/**
 * Renders the application layout with the given children.
 * @param children - the application content to render
 */

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const user = await initialProfile();
    const projects = await getProjectsByUsertId();

    if (user.role === "CLIENT"){
        return (  
            <div className="p-5 h-full w-full">
                <EmptyState
                    title="401"
                    subtitle="Unauthorized access"
                    fontSize="text-6xl"
                />
            </div>
        );
    }

  return (
    <div className=" h-full w-full overflow-hidden">
        <div className=" w-full h-full">
          {children}  
        </div>
        
    </div>
  );
}
