name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username:
        password:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose build
  
  
